Add composer to the project

diff --git a/.github/workflows/backend-deploy.yml b/.github/workflows/backend-deploy.yml
--- a/.github/workflows/backend-deploy.yml
+++ b/.github/workflows/backend-deploy.yml
@@ -82,7 +82,14 @@ jobs:
         run: |
           ssh "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" << 'EOF'
           cd ~/Docker/backend/dist
-          composer install --no-dev --prefer-dist --optimize-autoloader
+          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then >&2 echo 'ERROR: Invalid installer checksum'; rm composer-setup.php; exit 1; fi
+          php composer-setup.php --quiet
+          rm composer-setup.php
+          php composer.phar install --no-dev --prefer-dist --optimize-autoloader
+          rm composer.phar
           EOF
 
           
